#!/bin/bash
#
# chrome-alt
# ==========
# Launches a parallel Chrome instance with a different user profile.
# Profiles are just specified as a name (e.g. "dev"), not a full path.
# A default profile can be set via the $DEFAULT_CHROME_ALT_USER
# environment variable. Otherwise, it takes all the usual Chrome args.
#
# Written by Nathan Winant (www.exegetic.net |  nw@exegetic.net)


ARGS="${@}"
CHROME_ALT_USER=$DEFAULT_CHROME_ALT_USER

if [[ $(uname) == 'Darwin' ]] ; then
  BASE_USER_DATA_DIR="$HOME/Library/Application\ Support/Google/ChromeAltAccounts"
  CHROME_COMMAND="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
else
  BASE_USER_DATA_DIR="$HOME/.config/google-chrome-alt-accounts"
  CHROME_COMMAND=google-chrome
fi

if [ "$1" == "--help" ] ; then
  CHROME_ALT_USER=
elif [[ "$1" =~ ^--user=.* ]] ; then
  CHROME_ALT_USER=${1:7}
  ARGS="${@:2}"
fi

if [ -z "$CHROME_ALT_USER" ] ; then
  SCRIPT_NAME=$(basename $0)
  echo "Usage: ${SCRIPT_NAME} [--user=CHROME_ALT_USER] [standard Chrome args...]"
  echo
  echo "        Launches a parallel Chrome instance with a different user profile."
  echo "        Profiles are just specified as a name (e.g. \"dev\"), not a full path."
  echo "        A default profile can be set via the \$DEFAULT_CHROME_ALT_USER"
  echo "        environment variable. Otherwise, it takes all the usual Chrome args."
  echo
  echo "        * CHROME_ALT_USER may only be omitted if the \$DEFAULT_CHROME_ALT_USER"
  echo "          environment variable has been set."
  echo "        * All user profiles will be created in/retrieved from"
  echo "          $BASE_USER_DATA_DIR/[CHROME_ALT_USER]"
  echo
  echo "        Examples:"
  echo
  echo "          ${SCRIPT_NAME} --user=dev google.com yahoo.com"
  echo
  echo "          export DEFAULT_CHROME_ALT_USER=dev"
  echo "          ${SCRIPT_NAME} google.com yahoo.com"
  echo
  echo "        See also:"
  echo "          http://www.chromium.org/user-experience/user-data-directory"
  echo "          http://peter.sh/experiments/chromium-command-line-switches/"
  echo
  exit 1
fi

USER_DATA_DIR="${BASE_USER_DATA_DIR}"/"${CHROME_ALT_USER}"
COMMAND_STRING="$CHROME_COMMAND --user-data-dir=${USER_DATA_DIR} $ARGS > /dev/null 2>&1 &"
echo "Launching Chrome for user profile \"${CHROME_ALT_USER}\""
eval $COMMAND_STRING

