#!/usr/bin/perl
# 
# Performs 'ls', but exclusively on directories.
# Takes all the usual ls flags.
#
# Written by Alloni Kramer (allonikramer@gmail.com)
# Tweaked by Nathan Winant (www.exegetic.net | nw@exegetic.net)


$opt = "";

foreach $cmdl (@ARGV)  {
  if ($cmdl =~ /^-/)  {
    $opt .= " $cmdl";
  }  else {
    if (!-e "$cmdl")  {
      print "No such directory \"$cmdl\".\n";
    }  elsif (!-d $cmdl)  {
      print "\"$cmdl\" is a file, not a directory.\n";
    }  else  {
      push(@dirs, $cmdl);
    }
  }
}

if (!($#dirs + 1))  {
  push(@dirs, ".");
}

foreach $dir (@dirs)  {
  opendir(DIR, $dir);
  foreach $file (readdir(DIR))  {
    next if ($file =~ /^\.\.?$/);
    next unless (-d "$dir/$file");
    $file =~ s/\\/\\\\/g;
    $file =~ s/\"/\\"/g;
    $file = "\"" . $file . "\"";
    if ($dir eq ".")  {
      push(@out, "$file");
    }  else {
      push(@out, "$dir/$file");
    }
  }
}

print `ls -d $opt @out`;
